### ISSUE TITLE
For short case, how do you get bidaf result in the Table3 in the paper?

### ISSUE THREAD

**Issue by becxer** [bdhingra/quasar#2]
Now I'm trying to replicate result of table in the paper
But there are few things I couldn't able to found in the paper.

1. One is collecting strategy of making merged short 10 document which is mentioned in table3, Optimal Context collumn.  Is it meaning top 10? or randomly selected to get highest validation set score? 
2. Second is how did the sorting above all merged 10 answers?
3. Lastly, For bidaf-case short experiment which collected 10, seem to be same size with bidaf-case in long experiment. (short-case have average character size 200 * 10 and long-case have 2048 character) Is it right?

**Comment by bdhingra** [comment]
1. It means top 10. We conduct experiments with top-K articles selected, and report the results for the value of K which had the highest validation set performance.

2. Once we select the top-K articles, we concatenate them into one document, and use that as the input to the reading comprehension (RC) model. The RC model selects only one answer from this large document.

3. 200 and 2048 are the maximum character sizes we truncate short or long documents to, not the average sizes. Hence while the maximum document size for short with top-10 and long with top-1 will be different, the average might be quite different. Also note that these come from different document pools altogether -- long documents are full webpages, while short documents are sentences.
